package com.webset.set.egresos.dao;

import java.util.Date;
import java.util.List;
import java.util.Map;

import com.webset.set.egresos.dto.BitacoraPropuestasDto;
import com.webset.set.egresos.dto.BloqueoPagoCruzadoDto;
import com.webset.set.egresos.dto.ColoresBitacoraDto;
import com.webset.set.egresos.dto.ComunEgresosDto;
import com.webset.set.egresos.dto.ConsultaPropuestasDto;
import com.webset.set.egresos.dto.PagosPropuestosDto;
import com.webset.set.egresos.dto.ParamConsultaPropuestasDto;
import com.webset.set.traspasos.dto.GrupoDTO;
import com.webset.set.traspasos.dto.RubroDTO;
import com.webset.set.utilerias.dto.GrupoEmpresasDto;
import com.webset.set.utilerias.dto.LlenaComboDivisaDto;
import com.webset.set.utilerias.dto.LlenaComboEmpresasDto;
import com.webset.set.utilerias.dto.LlenaComboGralDto;
import com.webset.set.utilerias.dto.MovimientoDto;
import com.webset.set.utilerias.dto.SeleccionAutomaticaGrupoDto;
import com.webset.set.utilerias.dto.StoreParamsComunDto;


public interface ConsultaPropuestasBDao {
	public List<LlenaComboGralDto>llenarComboGral(LlenaComboGralDto dto);
	public List<LlenaComboGralDto>llenarComboBeneficiario(LlenaComboGralDto dto);
	public Date consultarFechaHoy();
	public String consultarConfiguraSet(int indice);
	public Date obtenerFechaHoy();
	public boolean validarUsuarioAutenticado(int idUsr, String psw);
	public List<SeleccionAutomaticaGrupoDto> consultarSeleccionAutomatica(ConsultaPropuestasDto dtoIn);
	public List<LlenaComboGralDto> llenarComboGrupoEmpresa(GrupoEmpresasDto dto);
	public int seleccionarPropuestos(String cveControl);
	public int seleccionarPagados(String cveControl);
	public String seleccionarRechazados(String cveControl);
	public List<String> seleccionarNombresUsuarios(int idUsuario1, int idUsuario2, int idUsuario3);
	public List<MovimientoDto>consultarDetalle(PagosPropuestosDto dto);
	public List<SeleccionAutomaticaGrupoDto> seleccionarPropGral(int idGrupoEmpresa, int idGrupo, String cveControl);
	public int actualizarAutorizacionPop(String campo, String valor, int idGrupo, String cveControl);
	public int selectCveCtrl(String cveControl,int noEmpresa);
	public int confirmaEliminar(String cveControl, int noEmpresa);
	public int deletePropuesta(String cveControl);
	//public List<MovimientoDto> buscaChequeras(List<MovimientoDto> listDetProp);
	public List<ParamConsultaPropuestasDto> nombreUsuarios(String usr1, String usr2, String usr3);
	public List<Map<String, Object>> reporteDetalleCupos(PagosPropuestosDto dto);
	public int actualizaPropuesta(String foliosCancela, String fecHoy, int noUsuario, String cveControl, int bandera);
	public List<ParamConsultaPropuestasDto> buscaRegistroBitacora(String foliosCancela);
	public int insertaLogPropuestas(int noEmpresa, String noDocto, String invoice, String concepto, int usuario, String fecha, String hora);
	public List<ParamConsultaPropuestasDto> buscaMovimiento(String foliosCancela);
	public int insertaBitacoraCheque(ParamConsultaPropuestasDto objPropuestasDto);
	public int actualizaNoCheque(ParamConsultaPropuestasDto objPropuestasDto);
	public List<ParamConsultaPropuestasDto> buscaSolicitudACancelar(String foliosCancela);
	public Map<String, Object> ejecutarRevividor(ParamConsultaPropuestasDto objPropuestas);
	public boolean verificaEstatusProp(String cveControl);
	public int updateMontosCupo(String cveControl, double importe);
	public int updateMontosAut(boolean suma, double importe, String cveControl,double importeS);
	public int updatePropSinRech(String cveControl);
	public List<Map<String, Object>> reporteConSelecAut(ParamConsultaPropuestasDto dto);
	public int validaFacultad(int idFacultad);
	public List<LlenaComboDivisaDto>llenarComboDivisa();
	public double obtenerTipoCambio(String sDivisa, Date fecHoy);
	public List<LlenaComboGralDto>llenarComboBancoPag(String sDivisa, String noEmpresa);
	public List<LlenaComboGralDto>llenarComboChequeraPag(int idBanco, int noEmpresa, String sDivisa);
	public List<ComunEgresosDto>buscaBancoChequera(int noEmpresa, int formaPago);
	//public boolean buscaFPProv(int noCliente, int formaPago);
	public int actualizarBCBenef(int noEmpresa, int noFolioDet, int idBanco, String idChequera, int formaPago);
	public List<ComunEgresosDto>buscaBancoChequeraBenef(int noCliente, String idDivisa);
	//public Map<String, Object> afectaCuadrantes(StoreParamsComunDto dto);
	public int actualizarFecPropuesta(String fecPago, String sFolios);
	public int actualizarFecPropuestaCupo(String fecPago, String cveControl);
	public int actualizarBanCheqPropuesta(String sFolios, int formaPago, int idBanco, String idChequera, int idBancoBenef, String idChequeraBenef, boolean actualizaBeneficiario);
	public int autorizarDetalle(int iFolio, int usr1);
	public boolean existeReg(String iFolio, int usuario, boolean ban, boolean ban2, boolean ban3);
	public int modificarDetalle(int iFolio, String psCampo, int usuario);
	//public int validaTodasAutorizadas(String cveControl, String caso);
	//public int valTodasDesAutorizadas(String cveControl, String psCampo);
	public List<MovimientoDto> consultarDetPagos(int noCliente, String fecIni, String fecFin);
	public int updateMontoPropuesta(double importeResta, String cveControl);
	public List<MovimientoDto> selectMonto(String usr, String cveControl);
	public List<MovimientoDto> selectMontoOriginal(String cveControl);
	public int buscarRegPend(String cveControl);
	public int updateFirmaDos(String cveControl, int usr);
	public int verificaFormaPago(int noFolioDet);
	public int verificaRegPend(String cveControl, int noEmpresa);
	//public List<GrupoDTO> llenarComboGrupo(String idTipoGrupo, int noEmpresa);
	//public List<RubroDTO> llenarComboRubros(int idGrupo);
	//public int insertarFlujoMovtos(int noFolioMov, int idGrupo, int idRubro);
	//public int insertaDatosConta(List<Map<String, String>> listMovtos, int i);
	//public int existeFlujoMovtos(int noFolioDet);
	//public int updateDatosConta(List<Map<String, String>> listMovtos, int i);
	public int eliminarDetalle(int iFolio);
	//public Map<String, Object> autorizarModificaciones(SeleccionAutomaticaGrupoDto dtoGMaster);
	public int updateFecProp(String cveControl, String fecha);
	public int updateFecDetProp(String cadControl, String fechaActualiza);
	public List<BloqueoPagoCruzadoDto> consultaPagosCruzados(String noPersona, boolean esNumero);
	List<LlenaComboGralDto> llenarComboBenefPagoCruzado(String noPersona, boolean esNumero);
	public List<LlenaComboDivisaDto> obtenerDivisas();
	public int insertaNuevoProvPagoCruzado(BloqueoPagoCruzadoDto pagoCruzado);
	public boolean existeProvPagoCruzado(String proveedor, String divisaOrig);
	public int eliminarProvPagoCruzado(String noProv, String divOriginal);
	public int existeBloqueo(String noEmpresa, String noProv, String noDocto);
	public List<BloqueoPagoCruzadoDto> obtenerBloqueoProveedor(String noEmpresa, String noProv, String cveControl, String noDocto);
	public int insertarBloqueo(String noEmpresa, String noProv, String noDocto, String motivo, int noUsuario);
	public int eliminarBloqueo(String noEmpresa, String noProv, String noDocto);
	public List<BloqueoPagoCruzadoDto> buscarBloqueo(String noEmpresa, String noProv, String noDocto, boolean existe,
			String periodo);
	public List<List<Object>> datosExcelBloqueados(int num);
	public List<BloqueoPagoCruzadoDto> consultaProveedoresBloqueados(String empresas, String propuestas);
	public List<LlenaComboGralDto> llenarComboPeriodos(LlenaComboGralDto dto);
	public List<LlenaComboGralDto> llenarComboReglaNegocio(LlenaComboGralDto dto);
	public List<LlenaComboGralDto> llenarComboChequeraPagBenef(int idBanco, int noEmpresa, String sDivisa, int idBenef);
	public Map<String, String> validaCvePropuesta(String cveControl);
	public Map<String, String> insertaSubPropuesta(double montoMaximo, String cveControl, String oldCveControl, int idUsuario, String fecha);
	public Map<String, String> actualizaMontoPropuesta(double montoMaximo, String cveControl, String stencero);
	public Map<String, String> actualizaPropuesta(String nvaCveControl, String noDoctos, String oldCveControl, String fecha);
	public List<LlenaComboGralDto> llenarComboGrupoEmpresaUnica(GrupoEmpresasDto dto);
	public Map<String, String> insertaBitacoraPropuesta(List<BitacoraPropuestasDto> listBitacora);
	public int validaFacultadUsuario(String facultad);
	public List<LlenaComboGralDto> llenarComboBancoPagBenef(String sDivisa, int noPersona);
	public int noExisteChequeraBenef(String cveControl);
	public int existeChequeraBenef(MovimientoDto movimientoDto);
	public List<LlenaComboEmpresasDto> llenarComboEmpresa(int usuario);
	//public int validarBancoChequera(List<SeleccionAutomaticaGrupoDto> listSeleccion);
	public List<String> validarBancoChequeraPagadoraBenef(String clavesControl, int tipoConsulta);
	public List<BloqueoPagoCruzadoDto> obtenerBloqueoSAP(String cveControl, String noDocto);
	public Map<String, String> actualizaMultisociedad(String cveControl, StringBuffer folios, MovimientoDto movDatos);
	public int modificadoMultisociedad(String cveControl);
	public List<MovimientoDto> consultarDetalleStored(PagosPropuestosDto consDetalleDto);
	public String eliminarDetalleStored(String cveControl, double importeTotal, double pdImporte, String foliosCancela,
			int noUsuario, int noCheque, String estatusPropuesta);
	public int consultaPropInterbancario(String cveControl);
	public List<SeleccionAutomaticaGrupoDto> consultarSeleccionAutomaticaStored(ConsultaPropuestasDto dtoIn);
	public List<ColoresBitacoraDto> obtenerColoresPropuesta();
	public List<ColoresBitacoraDto> obtenerColoresDetalle();
	public int consultaRFC(String cveControl);

}
